### ISSUE TITLE
version of library

### ISSUE THREAD

**Issue by mojtaba391** [ClusterWS/ClusterWS-Client-Java#3]
hi 
i added this line to my build.gradle file:
 implementation  'com.github.ClusterWS:ClusterWS-Client-Java:1.1.1'
 Has the correct version been added?

**Comment by Yegorisa** [comment]
Dear @mojtaba391 
l have released a new version of the library. The current version is 3.0.1 which is shown on the main page. 
Sincerely,
Egor

**Comment by Yegorisa** [comment]
Resolved
